### ISSUE TITLE
After MouseInterceptor has actioned, further clicks in a textbox will actually remove focus.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#101]
**QuitarHero at 8/23/2019 6:18:55 PM +00:00**
> **Bug Report:**
> > **Module:** Universal Search (Landmark)
> > **Build:** v0.4.2-dev+203
> **Issue:** When attempting to type in the landmark "search" field, your mouse cursor reverts to your normal desktop cursor, allowing you to type in said module.
> After a single click, it allows you to search in the landmark module's search field.
> *Any further clicks* will prevent you from interacting with the search field.
> The current, temporary fix, is to click off of the module's window (whether in-game or not) and re-click the search field.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/614523984897245184

**Comment by dlamkins** [comment]
@nickcode122's issue appears related: 
https://discordapp.com/channels/531175899588984842/534492012263636992/614541246320476377
https://cdn.discordapp.com/attachments/534492012263636992/614541651872055296/2019-08-23_15-28-08.gif
