### ISSUE TITLE
GetGw2PathFromRegistry() can fail under some circumstances

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#103]
**lei at 8/24/2019 12:37:45 AM +00:00**

Blish HUD v0.4.3-dev+204
08:32:19.4258|INFO|Blish_HUD.Program|Running PreRelease "dev"
08:32:19.4258|INFO|Blish_HUD.Program|Running Build "204"
08:32:20.2238|FATAL|Blish_HUD.DebugService|Blish HUD encountered a fatal crash!
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Blish_HUD.GameIntegrationService.GetGw2PathFromRegistry()
   在 Blish_HUD.GameIntegrationService.DefineSettings(SettingCollection settings)
   在 Blish_HUD.BlishHud.Initialize()
   在 Microsoft.Xna.Framework.Game.DoInitialize()
   在 Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   在 Blish_HUD.Program.Main()

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/614619323876769793

**Comment by dlamkins** [comment]
Exception doesn't seem to indicate the line.  The only thing I can imagine that could throw a NullReferenceException would be the BaseKey if it just failed to open for some reason.  I'm not sure if this is something I've overlooked or if this is something unique to the locale set on the computer as I'm not sure why the HKLM would be unavailable.

**Comment by dlamkins** [comment]
This is the first time I've seen this fail at this particular spot which is what makes me lean towards it being something to do with the locale or SKU.
