### ISSUE TITLE
Locale with dotless "i" will cause ContentLoadExceptions

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#118]
**hayspat at 8/31/2019 5:07:54 PM +00:00**
> Microsoft.Xna.Framework.Content.ContentLoadException: The content file was not found. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\Faruk\Downloads\Blish_HUD_v0.4.3-dev204\Content\fonts\menomonia\menomonia-12-ıtalic.xnb'.

REF: https://discordapp.com/channels/531175899588984842/599270434642460753/617405217482211368

**Comment by dlamkins** [comment]
Fixed by #120
