### ISSUE TITLE
Festival Service

### ISSUE THREAD

**Issue by greaka** [blish-hud/Blish-HUD#123]
Copy Paste from #62:

> this is more of a request for discussion:
theres not really a way to predict exact timings of annual events
so what would you say if the marker module had an optional(!) service that it would call thats gets timings for events. we would have to manually insert those events (so every 2 months putting in some times), the festival service (because maybe some other module could benefit from it?) would either expose if it can reach the service at all (kinda like arcdps service currently) or default to every event active when the service is unreachable
that way we could expose markers to hide depending on festivals
> 
> ![example image](https://cdn.discordapp.com/attachments/534490472224391169/601637629221666856/unknown.png)
> 
> ref: https://discordapp.com/channels/531175899588984842/534490472224391169/601637629221666857

Since the discussion derailed into a new context system and this system is in place now, we can now talk about the actual festival service

**Comment by dlamkins** [comment]
Updating here to indicate where things currently, the path I am currently taking, and a dump of some of my notes.

Archomeda mentioned using https://api.guildwars2.com/v2/achievements/groups/18DB115A-8637-4290-A636-821362A3C4A8 which appears to be our best path forward.

Ultimately, this returns a list of category IDs representing daily categories.  It appears that during festivals, this list will contain the IDs of the festival dailies as well.

Note:
- This group ID (GUID in the request above) represents the Dailies group.
- I have confirmed that it is currently showing the "Halloween Daily" (79) category within the current dailies.
- [A list of the currently possible daily options (throughout the year) is easily visible here, for reference.](https://en.gw2treasures.com/achievement#18DB115A-8637-4290-A636-821362A3C4A8)  I've included a list of these, with their festival names, below.
- There is a **Lunar New Year Dailies** (102) daily in the category that always shows and is not the real one.  The correct category is **Daily Lunar New Year** (201).  The invalid one contains no achievements.

Here are the festivals which provide category IDs in the dailies group:
- Halloween (79)
- Wintersday (98)
- Super Adventure Festival (162)
- Lunar New Year (201)
- Festival of the Four Winds (213)
- Dragon Bash (233)

~~[Currently Gw2Sharp appears to have a bug when requesting endpoints by GUID.](https://discordapp.com/channels/384735285197537290/589031897963692034/635798773813084170)  The GUID in the URL is provided in lowercase and the /v2/achievements/groups/ endpoint only accepts them in uppercase.~~(This was fixed here: https://github.com/Archomeda/Gw2Sharp/issues/22 and is included in v0.7.3)  This is currently preventing the remainder of the implementation.  EDIT: We will need to update to v0.7.3 unless https://github.com/arenanet/api-cdi/issues/657 is resolved.

In the meantime, I'm going to use Fiddler to rewrite the URL to at least allow me to test the implementation and will likely PR it as a draft so we can review the implementation in the meantime.

Ultimately, we'll likely need to upgrade to the latest version of Gw2Sharp once a fix is put in place which will be a small project on its own as we'll likely need to convert quite a bit over to the new namespaces and clients used now (introduced when the library began supporting MumbleLink).

**Comment by dlamkins** [comment]
Implemented in #131.  Support in the Markers and Paths module will be handled by https://github.com/blish-hud/Community-Module-Pack/pull/53
