### ISSUE TITLE
Blish HUD shows in the taskbar which makes it also visible when pressing ALT + TAB.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#124]
**Ɗ.ŁΔŴ at 4/20/2019 8:05:57 PM +00:00**
> Btw, is it supposed to be like this when u alt tab? The hud showing up like a tab?
![image](https://user-images.githubusercontent.com/1950594/64396562-030f8d00-d02c-11e9-8b5e-5280fd0194c4.png)

REF: https://discordapp.com/channels/531175899588984842/534492012263636992/569252438926688269

**Comment by dlamkins** [comment]
Added an option (defaults to "do not show") to toggle showing in the taskbar in #126.
