### ISSUE TITLE
`ScreenNotification` control does not allow the mouse to click through it.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#130]
**Greaka at 10/3/2019 2:11:12 PM +00:00**
> > **bug report**
> bhud notifications (not the ones in the upper left corner, the text ones) steal focus

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/629319548096610319

**Comment by agaertner** [comment]
encountered the problem a lot lately as I am starting to use this class more and more.
