### ISSUE TITLE
fieldOfView <= 0 or >= PI

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#145]
**Ni at 11/30/2019 3:39:22 PM +00:00**
> Well yeah.. it crashed 15 hours ago :x
> ```01:18:45.8048|FATAL|Blish_HUD.DebugService|Blish HUD encountered a fatal crash!
> System.ArgumentException: fieldOfView <= 0 or >= PI
>    at Microsoft.Xna.Framework.Matrix.CreatePerspectiveFieldOfView(Single fieldOfView, Single aspectRatio, Single nearPlaneDistance, Single farPlaneDistance, Matrix& result)
>    at Blish_HUD.CameraService.Update(GameTime gameTime) in E:\C#\BlishHUD\Blish HUD\GameServices\CameraService.cs:line 34
>    at Blish_HUD.BlishHud.Update(GameTime gameTime) in E:\C#\BlishHUD\Blish HUD\BlishHud.cs:line 128
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.Tick()
>    at MonoGame.Framework.WinFormsGameWindow.RunLoop()
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
>    at Blish_HUD.Program.Main() in E:\C#\BlishHUD\Blish HUD\Program.cs:line 45```

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/650360233939566622

**Comment by dlamkins** [comment]
Fixed in #172!

FieldOfView is now clamped when read from the MumbleLink API.
