### ISSUE TITLE
POI IconFile attribute overwritten by MarkerCategory

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#148]
**QuitarHero at 12/6/2019 9:01:38 PM +00:00**
> > **Bug Report:**
> **Module:** Core / Markers & Paths
> **Builds with Issue:** 242, 276
> **Issue:** In `MarkerCategory`, when specifying an icon for a category via `iconFile`, it overwrites all marker-specific icons with the category's icon.
> 
> Issue Example:
> ```XML
> <OverlayData>
>   <MarkerCategory name="PoF" iconFile="Data/PoF/Act2.png"/>
> 
>   <POIs>
>     <POI MapID="1234" xpos="1234" ypos="1234" zpos="1234" GUID="123412341234123123412==" type="PoF" iconFile="Data/PoF/pic1.png"
>     <POI MapID="1234" xpos="2345" ypos="2345" zpos="2345" GUID="234523452345234523==" type="PoF">
>   </POIs>
> </OverlayData>
> ```
> So what this shows is that the `MarkerCategory` has a defined `iconFile` attribute. **How it should work** is if a marker does *not* have an `iconFile` associated with it, it defaults to its marker category `iconFile`. If a marker *does* have its own `iconFile` attribute defined, it takes priority over the category's `iconFile`.
> 
> **The issue is** that the category's `iconFile` takes priority over all marker defined `iconFile` attributes, which is different than TacO since it prioritizes marker's `iconFile` over category `iconFile`
> 
> So in the ideal world, using the example, the first marker uses `pic1.png`, while the second marker uses `Act2.png`, but the issue makes both markers use `Act2.png`

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/652615662119813170

**Comment by dlamkins** [comment]
Fixed in #197
