### ISSUE TITLE
Scroll wheel rate is based on panel height instead of being constant.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#150]
**QuitarHero at 12/8/2019 8:06:00 PM +00:00**
> > **Bug Report:**
> **Module/Build:** Events and Metas Observer v0.44, Blish v0.4.6+dev276
> **Issue:** A minor issue, but when you go to scroll on the list of all events, it takes 2 scroll "clicks" to begin scrolling and it scrolls twice. Any subsequent scrolling afterwards only requires 1 scroll "click". This issue is only present when you try to scroll through the list when it's not already scrolling.
> 
> Issue may only be present on some mice, not all (since different mice have different scroll wheels)

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/653326434999337010

**Comment by dlamkins** [comment]
RCA determined here: https://discordapp.com/channels/531175899588984842/536970543736291346/664457001430155285

> I found an issue with the scrollbar that was contributing to its weird feel when used.  It would only scroll if you incremented the wheel fast enough that the smooth scrolling animation from the first would get canceled by the second (so you had to scroll at least twice within .35 seconds).  I'll get a seperate PR out for that.
