### ISSUE TITLE
3D entities are not LERP'ed 

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#165]
**QuitarHero at 2/6/2020 7:09:33 PM +00:00**
> > **Bug Report:**
> Taco and Blish don't share the same marker "stability" (framerate?).
> This was taken on a 144hz 1440p monitor.

https://gfycat.com/ornateconcernedkob
(Original video from Discord: https://cdn.discordapp.com/attachments/534492173362528287/675055501418954752/blish_icon_bug.mp4)

_Summary: the Blish HUD marker appears out of sync with the rest of the game when the camera is moved quickly and the game's framerate exceeds the overlay's framerate.  The TacO marker appears to stay mostly in the correct place, likely due to the lerping it implements on the MumbleLink data._

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/675055501960151041

**Comment by dlamkins** [comment]
Message from Discord:

> Oh, part of why the marker seems weird, too, is that in addition to the lerping, TacO in some earlier versions (before the 2019 builds) did not limit FPS which was also why it was so crazy on CPU.  Release builds of Blish HUD framelock to 60 which will cause markers to look sluggish if the game is rendering faster.  I do believe the TacO release a few months ago implemented a FPS limiter, though, so I'm guess it's the lerping helping it out now.  When I get the new Gw2Sharp implemented, I'm going to try and decouple the Gw2MumbleLink service from the update loop so that it can hover around the same pace as the game renders and help occasionally guide the overlays target FPS.
> 
> In my testing lerping helped some if the pull rate was below, but it made things look a bit worse if the overlay was keeping pace with the game's framerate and that's why I ended up disabling it (when I'm in debug builds, the FPS isn't locked and is pretty much always well above the game FPS).  It may have been better to leave it (since release builds are FPS limited anyways) until the decoupling happened.  The FPS limiting will be optional in Blish HUD once I get the service decoupled and I can get the lerping re-added as well.
> 
> TacO actually lerps all of the MumbleLink data it reads in before anything touches it.  Should I have it do that when lerping is enabled so that all consuming services benefit, or should I leave it to the consuming services to handle the raw data how they would like (since the raw data may be more important to some things).  Perhaps I can just have a set of calls that return explicitly the latest raw values and then others that return the interpreted (raw if lerping is disabled or the calculated value if lerping is enabled).

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/675270215055179806
