### ISSUE TITLE
MapVirtualKey returns dead key indicator causing overflow

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#167]
**V3ntr1s at 3/7/2020 11:38:00 AM +00:00**
> bhud crashes on any key press, I have unloaded all modules to make sure it's not some module issue. Im using "Standard keyboard" layout in windows.

> Blish HUD v0.4.5-dev+287
> 12:29:53.5383|INFO|Blish_HUD.Program|Running PreRelease "dev"
> 12:29:53.5463|INFO|Blish_HUD.Program|Running Build "287"
> 12:29:55.7665|WARN|Blish_HUD.OverlayService|Failed to detect current Guild Wars 2 client version: "The build ID reported by the Mumble Link API (102510) could not be matched against a CDN provided build ID."
> 12:29:55.8739|INFO|Blish_HUD.OverlayService|Detected Guild Wars 2 client to be the Standard version.
> 12:30:32.6611|FATAL|Blish_HUD.DebugService|Blish HUD encountered a fatal crash!
> System.TypeInitializationException: The type initializer for 'Blish_HUD.Input.KeysUtil' threw an exception. ---> System.OverflowException: Value was either too large or too small for a character.
>    at System.Convert.ToChar(Int32 value)
>    at Blish_HUD.Input.KeysUtil..cctor()
>    --- End of inner exception stack trace ---
>    at Blish_HUD.Input.KeysUtil.ModifiersFromKeys(IEnumerable`1 keys)
>    at Blish_HUD.Input.KeyboardManager.Update()
>    at Blish_HUD.BlishHud.Update(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.Tick()
>    at MonoGame.Framework.WinFormsGameWindow.RunLoop()
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
>    at Blish_HUD.Program.Main()

> tested with "US keyboard" layout and it's working fine. If I switch back to "Standard" while blish is running it's still fine, once I restart blish with "standard" layout it crashes again.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/685813500848766978

**Comment by dlamkins** [comment]
Found two issues.

`MapVirtualKey` in the `KeysUtil` should be returning `uint`.  Additionally, `MapVirtualKey` is indicating when the provided key is a dead key, which was not accounted for.  `MapVirtualKey` does this by setting the highest byte.  This causes an overflow when we go to convert the returned value to a char.
