### ISSUE TITLE
Make user settings path an option.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#169]
**Bennieboj at 3/13/2020 8:15:42 PM +00:00**
> Is it possible to let BHUD use a folder inside the application folder (instead of %USERPROFILE%\Documents\Guild Wars 2\addons\blishhud), thus making it truly self contained?

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/688118110368170007

**Comment by dlamkins** [comment]
Implemented in #171 

`& ".\Blish HUD.exe" --settings .\`
