### ISSUE TITLE
Menus should go up before getting cut off screen.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#187]
**Snaid1 at 4/14/2020 3:25:41 AM +00:00**
> 2 suggestions for the markers module:  1)I'm sure it was already suggested, but add an option to dim paths that are around the player (similar to how gw2taco does). 2) adjust the spacing or font or shift menus up for people that have a lot of markers/packs (See screenshot for issue, I know I need to clean up my markers folder).

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/699460344137121862

**Comment by dlamkins** [comment]
We've done something with the DropDown control which we should be able to replicate with the ContextMenuStrip control.

**Comment by dlamkins** [comment]
The primary issue has been resolved in #257.

Marker dimming will be handled in the module  itself.
