### ISSUE TITLE
ScrollDistance and TargetScrollDistance out of sync

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#198]
**QuitarHero at 4/28/2020 2:07:47 PM +00:00**
> > **Bug Report:**
> > **Version:** 358
> **Issue:** When using the scroll arrows to scroll around, and then use a mouse wheel scroll click, it will only scroll up or down to a certain point (based on your windows scroll speed).
> **Showcase:** https://gfycat.com/wickedblandgalapagostortoise

https://gfycat.com/wickedblandgalapagostortoise

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/704695366184075355

**Comment by dlamkins** [comment]
> There are two ways that the scroll position is set depending on the input method.  One is internal and is to drive the smooth scroll animation.  The other snaps it which is what the arrows are doing.  It is likely getting it out of sync with the animation targets causing it to not go as far as it should.

> Yeah, lol, that's exactly what it is.  If you want a laugh, use the arrows many times (so that the bar is further down than it would have done in a single scroll).  Then use your scroll wheel for a single click (if you have a smooth one, just try to do it as small as possible).  It'll actually make the bar go up in the wrong direction.  :laughing:
