### ISSUE TITLE
Modules tab doesn't show anything when selected.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#216]
**Sadrien at 5/9/2020 9:11:50 AM +00:00**
> going to the manage modules tab in settings on the latest version does not change the appearance of the page from the other tabs.

REF: https://discordapp.com/channels/531175899588984842/534492012263636992/708607152692133938

**Comment by dlamkins** [comment]
This is confusing when the user has no modules currently in the modules folder.

**Comment by dlamkins** [comment]
Fixed in #293
