### ISSUE TITLE
Option to manually set UI Size and ignore in-game UI size

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#229]
**Naillyk at 5/21/2020 9:50:38 AM +00:00**
> > To clarify, are you looking for a way to set the UI size of Blish HUD manually?  
> <@!164832069401182210> 
> 
> You couldn't be more spot on than that! 😄

REF: https://discordapp.com/channels/531175899588984842/531175900100952087/712965569674215485

**Comment by entrhopi** [comment]
This can be closed.

**Comment by dlamkins** [comment]
Closed by #547
