### ISSUE TITLE
Events module does not load the configuration properly

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#230]
**D.ŁΔŴ at 5/23/2020 7:17:18 PM +00:00**
> Have a problem with the meta event module. It resets to default every time i start blish, i usually turn of some meta i don't care about.  Is something wrong on my side or is it the module?

REF: https://discordapp.com/channels/531175899588984842/534492012263636992/713832955029618708

**Comment by dlamkins** [comment]
Fixed in a previous release.
