### ISSUE TITLE
[Debug Module] crashes Bhud when disabling

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#235]
**Tybalt at 5/23/2020 8:45:29 PM +00:00**
> the debug module still crashes bhud when disabling the module

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/713855145456435240

**Comment by dlamkins** [comment]
No longer an issue.  Latest Debug module copy does not crash Blish HUD.
