### ISSUE TITLE
HLSL Shader ignore Opacity of parent container.

### ISSUE THREAD

**Issue by TybaIt** [blish-hud/Blish-HUD#24]
Since the pipeline changes HLSL Shader (glow.fx, silhouette.fx, etc) ignore Opacity of parent container.

This is bad for fading containers with Image children which use shader.

EDIT: Most noticibly on the GuessCharacter hint from LoadingScreenHints module.

**Comment by agaertner** [comment]
Isn't this just a missing opacity variable in the fx file? I am clueless about HLSL, but I am taking a risky guess this could be closed quickly.
