### ISSUE TITLE
Do something about blank home tab in UI.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#256]
**Aens at 6/22/2020 1:13:21 AM +00:00**
> okay, well... consider a "there is nothing yet" message or something, to avoid confusion for newbies like me xD

REF: https://discordapp.com/channels/531175899588984842/534492012263636992/724431804429238311

**Comment by dlamkins** [comment]
I think we'll opt to remove the home tab for now until the intended content is actually ready to be displayed there.

**Comment by dlamkins** [comment]
Closed by #259
