### ISSUE TITLE
Tweak GitVersion

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#272]
**Archomeda at 7/2/2020 6:12:33 AM +00:00**
> technically you can also change this if you really want:
> ```yaml
> # use a variable if non-null or a fallback value otherwise
> assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{WeightedPreReleaseNumber ?? 0}'
> 
> # use an environment variable or raise an error if not available
> assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{env:BUILD_NUMBER}'
> 
> # use an environment variable if available or a fallback value otherwise
> assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{env:BUILD_NUMBER ?? 42}'
> ```

REF: https://discordapp.com/channels/531175899588984842/536970543736291346/728130980367433739

**Comment by dlamkins** [comment]
GitHub environmental variable details available here: https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
