### ISSUE TITLE
Main settings window leaving trailing artifacts when dragged,

### ISSUE THREAD

**Issue by davidlukerice** [blish-hud/Blish-HUD#281]
Downloaded Blish.HUD.0.5.2-dev.661 from the discord channel and tried to run it, but I'm getting a number of artifacts from the settings window when moving it around that never clear until I close out of BHUD. Happens even if I disable arcDPS.
![Screenshot 2020-07-15 19 05 56](https://user-images.githubusercontent.com/1794759/87618833-68b6b600-c6e0-11ea-81f2-7a7be25c2484.png)

OS: windows 10.0 Build 17134
GPU: AMD Radeon HD 7800 series, with v20.4.2 drivers

**Comment by dlamkins** [comment]
Thanks for those details!  Could you provide us a copy of the logs found under `%userprofile%\Documents\Guild Wars 2\addons\blishhud\logs`?

I've not seen this happen before.

**Comment by davidlukerice** [comment]
It looks to be fine until I focus on a window outside of GW2 and then come back in game. I'm using "Windowed Fullscreen" as my resolution, if that helps.

```
Blish HUD v0.5.2-alpha.661+Branch.dev.Sha.1cbb26a800c0581c03ef23e61bc6cde329533a25
10:52:33.0853 | INFO  | Blish_HUD.Program | Running PreRelease "alpha.661"
10:52:33.0853 | INFO  | Blish_HUD.Program | Running Build "Branch.dev.Sha.1cbb26a800c0581c03ef23e61bc6cde329533a25"
10:52:35.1752 | INFO  | Events_Module.Meta | Loaded 45 events.
10:52:35.3281 | INFO  | Blish_HUD.OverlayService | Detected Guild Wars 2 client to be the Standard version.
10:52:35.4601 | INFO  | Blish_HUD.Gw2WebApiService | Associated API key "saviorofliger.1762" with characters: "Sage Of Frost, Dawn Of The Heavens, Sage Of Dawn, Sneaky Sneaky Sage, Sage Of The Dragon, Unseeing Sage, Unholy Divination, Dawn Of Dreams, Xarasu"
10:52:35.4601 | INFO  | Blish_HUD.Contexts.FestivalContext | Active festival(s): ""
10:52:36.5757 | WARN  | KillProofModule.KillProofModule | A new version of the KillProof module was found: '1.5.4'.
10:52:36.5757 | INFO  | Blish_HUD.Modules.Module | Module "KillProof Module (KillProofModule) v1.5.3" finished loading.
10:52:36.5817 | INFO  | Blish_HUD.Modules.Module | Module "Events and Metas Observer (bh.general.events) v0.6.0" finished loading.
10:53:13.6909 | INFO  | Blish_HUD.ModuleService | Unloading module "Events and Metas Observer (bh.general.events) v0.6.0".
10:53:15.9062 | INFO  | Blish_HUD.ModuleService | Unloading module "KillProof Module (KillProofModule) v1.5.3".
```

**Comment by dlamkins** [comment]
Thanks!  Nothing looks out of place there, unfortunately. 

Does dragging a window over a spot with glitched graphics overwrite that area of glitched graphics?  It almost looks like the screen isn't properly clearing between frames - or, at least part of it isn't.  🤔

**Comment by dlamkins** [comment]
@davidlukerice Could you please run "winver" from the run dialog (windows key + R) and let us know what version of Windows it says you're running?

For example, this is what it shows for me:
![image](https://user-images.githubusercontent.com/1950594/88450403-aae8a180-ce1c-11ea-9765-ef1103aa3b2e.png)

**Comment by davidlukerice** [comment]
Yeah, dragging over the spot did redraw over it so it seemed like a clearing issue. Checked winver and was on Version 1803 of windows since it hadn't prompted to update. Manually checked and updated to Version 1909 and it looks to be working fine now.

**Comment by dlamkins** [comment]
@davidlukerice We did have a user that recommended that we check to see if you were on 1803 because supposedly there were issues with the Windows Game Bar and overlaying games as well in that version.  Can't say I know that was the root cause here, but we'll definitely make note of it in-case it comes up.

In any case, I'm glad to hear that it's working for you now that you've upgraded to 1909.

**Comment by SriRamanujam** [comment]
I'm seeing this even with a fully-updated GW2 and Win10 21H1, with latest Blish HUD 0.7.0. If it helps, I'm running an AMD R9 390.
