### ISSUE TITLE
Make meta notifications copy waypoint to clipboard.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#283]
**DAZTi at 7/16/2020 7:59:48 PM +00:00**

> Yo, any1 who made event ane meta tracker PLEASE! do it for me/us and add the TP copy to clipboard like here

![image](https://user-images.githubusercontent.com/1950594/88010265-7e621c00-cae2-11ea-994c-b2979beeae40.png)

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/733412593460314112

**Comment by dlamkins** [comment]
Resolved in https://github.com/blish-hud/Community-Module-Pack/pull/71
