### ISSUE TITLE
ArcDps crash on empty message

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#305]
**Freesnöw at 9/20/2020 7:53:34 PM +00:00**
> 🤔 interesting.  <@!243389466100760576> 
> 
> ```
> 14:51:36.6600 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Blish_HUD.ArcDpsService.MessageHandler(MessageData data) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ArcDpsService.cs:line 140
>    at Blish_HUD.ArcDps.SocketListener.ProcessReceivedData(Int32 dataStartOffset, Int32 totalReceivedDataSize, Int32 alreadyProcessedDataSize, AsyncUserToken token, SocketAsyncEventArgs e) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ArcDps\SocketListener\SocketListener.cs:line 139
>    at Blish_HUD.ArcDps.SocketListener.ProcessReceive(SocketAsyncEventArgs e) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ArcDps\SocketListener\SocketListener.cs:line 109
>    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
>    at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
>    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
> ```
> 
> (From QuitarHero: "i was just superspeed+quickness choya'ing in a frac")

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/757328626156044338

**Comment by greaka** [comment]
another discussion about it: https://discord.com/channels/531175899588984842/536970543736291346/805811006605099038

**Comment by dlamkins** [comment]
Hasn't been an issue in a long time.
