### ISSUE TITLE
Settings not force saved when Blish HUD is restarted.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#324]
**QuitarHero at 10/18/2020 6:14:13 PM +00:00**
> i think if you restart blish too fast after you swap a language it doesn't register that you actually swapped

REF: https://discordapp.com/channels/531175899588984842/534492012263636992/767450480250191893

**Comment by dlamkins** [comment]
Fixed in https://github.com/blish-hud/Blish-HUD/commit/d113e1f005b4387cfaaa3000e1e9e991b7dab585
