### ISSUE TITLE
New XML-Tag "Trigger" for Marker Packs

### ISSUE THREAD

**Issue by chland** [blish-hud/Blish-HUD#34]
So I had an idea and i can't decide if its utter garbage or totally brilliant :)

I never used any really big marker-pack before and just started using Tekkit's "All In One"-pack. And while the markers are brilliant, the useability is not so great.

And that got me thinking. We already have this idea floating around of markers being toggled on/off by completing achievements, etc.

So why not introduce the concept of "Triggers". Let me explain how this would work (VERY basic draft of the idea):

Lets say we have a marker like this one:

`<POI MapID="123" xpos="10" ypos="20" zpos="30" type="general.something.blah" GUID="svyyABEpykiEwxTepCSHdw==" />
`
but we want to hide it if the player has completed the "Tequatl the Sunless" achievement. So we create a new trigger:

`<Trigger type="achievement" achievement_id="910" trigger_id="achievements.tequatl">`

Now lets do some magic and hide our Marker if the player completed this achievement:

`<POI MapID="123" xpos="10" ypos="20" zpos="30" type="general.something.blah" GUID="svyyABEpykiEwxTepCSHdw==" hide_trigger="achievements.tequatl" />`

you might say: okay, nice - but why don't we just add an attribute to the POI that contains the achievement-id directly?

Good question! But here comes the "type" attribute of the Trigger into play.

Lets say we want to show the marker if the player is near a certain position

`<Trigger type="sphere" map="123" xpos="100" ypos="100" zpos="100" radius="500" trigger_id="random_position.somewhere" >`

and again:

`<POI MapID="123" xpos="10" ypos="20" zpos="30" type="general.something.blah" GUID="svyyABEpykiEwxTepCSHdw==" show_trigger="random_position.somewhere" />`

There could be a bunch of different trigger-types:

- `achievement` -> checks for an achievement
- `sphere` -> checks if the player is inside a sphere defined by xpos/ypos/zpos/radius
- `box` -> checks if the player is inside a box defined by xpos1/ypos1/zpos1 - xpos2/ypos2/zpos2
- `marker` -> if the player interacts with a marker, this trigger is toggled between true/false
- ???

We could alos add simple boolean-logic to the POI-attribute. So `hide_marker="xyz"` would hide a POI if trigger "xyz" is "true" while `hide_marker="!xyz"` would hide it if the trigger is false.

Like I said: that is basically just a VERY rough idea but I think it could be an interesting approach to make the whole marker-system a lot "smarter".

**Comment by dlamkins** [comment]
We've since gone a different direction with markers and I don't believe this is very relevant any more.  If things are redesigned in the future and this becomes applicable again, we'll reopen.

Thanks!
