### ISSUE TITLE
Auric Basin meta event times wrong

### ISSUE THREAD

**Issue by llama-ninja** [blish-hud/Blish-HUD#344]
The meta event time for auric basin appear to be wrong 
![image](https://user-images.githubusercontent.com/67041280/103115158-3bb5f880-46ad-11eb-80a9-33e780a08b93.png)

The battle in Tarir event should next start at 1:00 PM my time, not 1:30, as you can see here 
![image](https://user-images.githubusercontent.com/67041280/103115201-6607b600-46ad-11eb-927d-23229b5331e3.png)

**Comment by dlamkins** [comment]
Fixed in the next release of the module.  Thanks for reporting!

(Fixed by https://github.com/blish-hud/Community-Module-Pack/pull/100)
