### ISSUE TITLE
Module Settings Screen.  Mouse Scroll issues

### ISSUE THREAD

**Issue by manlaan** [blish-hud/Blish-HUD#375]
I've noticed that the mouse scroll moves too much.
To reproduce, either load a lot of module files, or create a module with a long list of settings.   
On my tests, on a module with 20 settings, it scrolls from the top to the bottom with one scroll bump, even through my windows scroll per is set to 4 (default?).   

I suggest changing Blish HUD/Controls/Scrollbar.cs - private const int SCROLL_WHEEL = 100;
40 seems to work a lot better, but might still be a little high.   

Also, on the Module Settings Screen, the scroll bar is unable to be dragged, and the up and down arrows are unable to be clicked.   I didn't really look to see where this is created, so no idea what is missing for this to work.

**Comment by dlamkins** [comment]
Fixed in #391, thank you!
