### ISSUE TITLE
Can't Paste API Key

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [blish-hud/Blish-HUD#379]
Tried doing Ctrl + V  where it says Register API Key, also tried right clicking to see if there was a menu to click paste.

Instead my character just dodges and nothing happens.  Also if I start typing in chat while  I have the cursor typing on Blish, they both type at the same time..

**Comment by dlamkins** [comment]
This is a bug reported by several of our users.  We're investigating and hope to have a fix in the next release (v0.8.0).

**Comment by dlamkins** [comment]
We'll track RCA in #419.

**Comment by dlamkins** [comment]
Fixed in #461 to be available in the latest release shortly.

**Comment by weiss-d** [comment]
Hi, @dlamkins!
I have the same issue with 0.11.7 and up-to-date GW
