### ISSUE TITLE
Expose enemy world coordinates?

### ISSUE THREAD

**Issue by John-Dean** [blish-hud/Blish-HUD#380]
Hi,

Is it be possible to have an API to expose the XYZ map coordinates of enemies? This would be so you could trigger things to happen when bosses phase and move position for example?

I've looked through the repo and documentation but I couldn't find anything that does this.

Thanks,
John

**Comment by greaka** [comment]
Sadly not. The game doesn't tell us about anything from enemies, not even that they exist.
We aren't allowed to take things in our own hands and since the game doesn't provide this data on its own, we cannot build anything that would expose such info.
