### ISSUE TITLE
UI should be generated using the MVP pattern.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#45]
Current UI pages are managed via singletons.  This is not scalable or flexible and we should switch to the MVP pattern to better handle this.

**Comment by dlamkins** [comment]
Asking for some insight on the MonoGame Discord was not particularly fruitful. https://discordapp.com/channels/355231098122272778/402546044274999299/600805102999306250

**Comment by greaka** [comment]
Which UI pages are not built with the MVP pattern currently?

**Comment by dlamkins** [comment]
Right now, the settings tab itself is the only remaining significant item on this list.  A more appropriate view would let other services / modules register their entries in the settings list instead of being manually specified as part of the Settings service.

Should be easy enough and is the only remaining item.  Modules aren't making use of them yet, but those won't hold this issue open as they can convert as necessary / where convenient.

**Comment by dlamkins** [comment]
Remaining items were resolved in https://github.com/blish-hud/Blish-HUD/pull/341
