### ISSUE TITLE
Detect mumble name from command line

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#452]
Detect mumble name from command line using `ManagementObject` to pull the CommandLine parameters.

Querying WMI is incredibly slow (like approaching full seconds) so we'll want to be mindful of this when implementing.  Ideally we'd give users the options to attach to an instance in the context menu strip or in UI if we manage to attach to an instance without detecting mumble connected.

**Comment by Friendly0Fire** [comment]
Is querying WMI in a worker thread feasible? Feels like that'd deal with any potential hiccup. You'd only want to run it after you've confirmed the newly focused window is a GW2 window, and then you'd associate the PID of that instance with its MumbleLink instance so it only needs to run once.

**Comment by dlamkins** [comment]
We'd most certainly be able to do that. Wanted to make note of it in case
somebody other than myself decided to try and implement it. 👍

**Comment by dlamkins** [comment]
Closed by #452
