### ISSUE TITLE
Trackbar jumps to wrong position when clicked.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#484]
https://i.gyazo.com/c185f613865f1ca38e36b02cbefc7044.gif
https://i.gyazo.com/bfde64ab95e0c0f4844d533fc246cba7.gif

The trackbar jumps when clicked on.  Appears to be made worse when the starting offset is non-zero.  Replicate with the setting:
![image](https://user-images.githubusercontent.com/1950594/135539317-6b65c6f5-61f1-4793-b3eb-d21cee45e010.png)

REF: https://discord.com/channels/531175899588984842/599270434642460753/892811075966349353

**Comment by entrhopi** [comment]
I tried to mitigate this by subtracting 29 from `_dragOffset` in https://github.com/blish-hud/Blish-HUD/blob/dev/Blish%20HUD/Controls/TrackBar.cs#L96 like so:
`var relMousePos = this.RelativeMousePosition - new Point(_dragOffset - 29, 0);`

This seems to lessen the effect but the closer you get to the left or right of the bar there will be a tiny drift to either side.

I will investigate this further.

**Comment by entrhopi** [comment]
Found part of the issue:
If a MinValue other than 0 is specified, then this would be the `wrong` slider offset as seen in the examples above.

Working on a fix now.

**Comment by dlamkins** [comment]
Closed by #556!
