### ISSUE TITLE
Alt-tab/Switching windows causes full-screen black flash

### ISSUE THREAD

**Issue by tuftelien** [blish-hud/Blish-HUD#533]
With BHUD Frame Limiter set to Sync With Game.

WIth other BHUD Frame Limiter settings menus still flash.
BHUD Vsync doesn't seem to change the behavior.

GW2 settings: Windowed Fullscreen, frame limiter unlimited, FPS 60-80

**Comment by dlamkins** [comment]
Hello!

This is a known issue related to how we handle frame synchronization to help keep CPU utilization low when the game framerate is low.

We'll  keep this issue to track alternative methods to how we handle frame syncing accuracy and our balance with CPU utilization.

In the meantime, If it is a common issue for you, I'd recommend setting Blish HUD to 90 FPS on the limiter with vsync enabled and in fact is our new default setting in the latest pre-releases. 👍

**Comment by dlamkins** [comment]
This should no longer be happening.
