### ISSUE TITLE
General workflow

### ISSUE THREAD

**Issue by greaka** [blish-hud/Blish-HUD#54]
I have a really hard time to figure out what is done in #43 and what for example, just got merged into the branch
So I would like to propose a general workflow for the future, so we are faster with reviews on prs like this.

First of all, please make seperate pr's for different stuff. 

Next, the general workflow (proposal):

1. `git fetch`
2. `git checkout origin/dev` - assuming origin is blish-hud/Blish-HUD
3. `git checkout -b <my-awesome-feature>`
4. do your work, commit often, push often
  a. if you need other changes in this pr, follow this:
  b. `git stash`
  c. go recursive to `1.`
  d. `git checkout <my-awesome-feature>`
  e. `git stash apply`
5. in the meantime, open a draft pr (so we can give feedback already)
6. `git fetch`
7. `git rebase origin/dev` - or another branch based on dev if you still wait for a pr to be merged, the rebase here is important
8. if you need to:
  a. commit
9. `git push`
10. `mark the draft pr as ready`

this ensures that our pr's are clean and easy to review
the easier to review, the faster we can move on to new features 😃 

PS: i dont mind if you have another workflow. i just dont want branches merged into your pr, because then i dont know what is really done in the pr without blaming through every file. and i dont want mixed pr's. thats just ugly and you lose track which change belongs to what feature/bug

I look forward to your comments :)

**Comment by dlamkins** [comment]
Okay, thanks for this write up!  I'm using Gitextensions that was recommended to me and it seems to do a much better job, so I should be good on my end now.  I've taken stuff back into my fork and should be set to PR from there from now on.

**Comment by TybaIt** [comment]
Github has evolved and you can use 
``git rebase --interactive``
https://help.github.com/en/articles/about-git-rebase
