### ISSUE TITLE
Greyscale shader

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#56]
@TybaIt is looking for a grayscale shader to be added to the project.

I should be able to write one and either merge it in with gw2master.fx if that is ready by the time the shader is written, or split it out as grayscale.fx until gw2master.fx is ready to act as the master shader.

REF: https://discordapp.com/channels/531175899588984842/599270434642460753/599616028707913769

**Comment by dlamkins** [comment]
Now that modules support loading their own shaders, I think this is out of scope for core to implement.

**Comment by agaertner** [comment]
I made one that supports Intensity now.
It is nice that we can import those from modules but awkward having to compile them first to MGFX. I also thought XNB was enough at first and was confused until I read up that for ``.GetTexture()`` we need to use MGFX.
<https://github.com/labnation/MonoGame/blob/master/Documentation/2mgfx.md>
``NOTE: The generated file is not an XNB file for use with the ContentManager.``

Was a bit confusing at first but works.
