### ISSUE TITLE
RTSS FPS counter overlay and BlishHUD

### ISSUE THREAD

**Issue by 6669024** [blish-hud/Blish-HUD#561]
I noticed my RTSS FPS counter overlay to be overlapping 2 different FPS numbers since installing BlishHUD. Not sure why it does this, but to fix it, I went into RTSS, made a new application profile for BlishHUD (click add on the bottom left, find BlishHUD.exe, select BlishHUD.exe) and changed the render mode for BlishHUD to Vector 2D. (select BlishHUD.exe on the left, select Vector 2D on the right under "On-Screen Display Render Mode")

**Comment by dlamkins** [comment]
One of the FPS counters would be for Blish HUD itself which is rendering not much unlike any other game would. 

Not much we can do to prevent 3rd party FPS counters from showing up on us, though, but good to know for anyone else that runs into this with that specific application.
