### ISSUE TITLE
Left Click with Mouse Cursor Module

### ISSUE THREAD

**Issue by M6D6M6A** [blish-hud/Blish-HUD#564]
I wanted to use the Mouse Cursor module, when I enable Show When Camera Drag and right click to move the camera it works the way I want. This way I can better hit my skillshots. But when I do the whole thing with left click the cursor moves illogically and is not where the skillshot would fly to, is there any way to fix this?

**Comment by dlamkins** [comment]
@manlaan This question appears better suited towards you for your module (https://github.com/manlaan/BlishHud-MouseCursor).

**Comment by manlaan** [comment]
The short answer to this is, as far as I'm aware, it isn't possible.  

The issue arises that if I stop movement of the graphic during the left holds, it would make it not follow when doing other things, like inside of inventory, for example.   I did think about doing it for that as well, but it became very disorienting.
