### ISSUE TITLE
Textbox remains selected when a window is closed with ESC.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#567]
We have two options for the behavior here.
- Both the textbox loses focus and the window is closed (this seems a bit more complicated).
- Just the textbox loses focus.

For anything that doesn't close with ESC, the latter would be the observed behavior, so for consistency and for simplicity, it's probably best that we just ensure that the windows don't close if a text field is selected (which should be easy enough).

**Comment by entrhopi** [comment]
See #549
