### ISSUE TITLE
Option to hide during cutscenes and loading screens.

### ISSUE THREAD

**Issue by luis86dr** [blish-hud/Blish-HUD#580]
Tried searching and couldn't find anything regarding if this was already a feature or possible? Basically what I'm referring to is the entire add on hiding iteself during cut scenes and loading screens. If not, maybe a suggestion for visual appearance? Love the project btw and really appreciate everyones hard work. <3

**Comment by dlamkins** [comment]
We can add this as an option, but we have to make sure it's an option because some users use Blish HUD while waiting for loading screens or while on the character select (which we can't detect the difference between character select, loading screens, and cut scenes).

**Comment by entrhopi** [comment]
We could spin out 'dynamic HUD' into a separate section in the settings and add this to it.
