### ISSUE TITLE
Allow setting the keybind for interaction

### ISSUE THREAD

**Issue by nalabelle** [blish-hud/Blish-HUD#582]
Since users can rebind it in the game, it should be editable without having to compile. Might only be used in the pathing module at the moment; that's where I noticed it.

https://github.com/blish-hud/Blish-HUD/blob/279c620296327bea48a2583046da1085cfb06c73/Blish%20HUD/Common/Gw2/KeyBindings.cs#L15

Referred to from here: https://github.com/blish-hud/Pathing/blob/f8bb925c33b7d13dcd6c77ad469a7a3d616b41dd/State/SharedPackState.cs#L50

**Comment by dlamkins** [comment]
Yes, this is definitely on the roadmap as plenty of folks do have this rebound.

We also hope to expose in-game keybindings automatically over the bridge DLL at some time in the future to help automate this and keep it in sync.
