### ISSUE TITLE
Add timer to event table tooltips

### ISSUE THREAD

**Issue by MackerelHunter** [blish-hud/Blish-HUD#583]
Hi, i have a small request. I think it would be a great idea if the event table could show a timer in the tooltip when hovering the events. 
Example: You hover over the next Doomlore Shrine event and the tooltip reads: "The Haunting of Doomlore Shrine - Grothmar Valley - 41:23" and it's ticking down.

**Comment by Tharylia** [comment]
Hi,
there was version 0.1.8 which already included that (without it ticking down, just static on every hover).
Unfortunately that version contained a major bug which resulted in the temporary deletion from the module repo.
It will be included again in the next fixed release which will probably come out today.

**Comment by dlamkins** [comment]
Version 0.1.9 is now live in the repo if you'd like to give it a shot @angstschweiss 👍

**Comment by MackerelHunter** [comment]
Thank you for the fast replies. Unfortunately i'm not very familiar with github. Where can i find the file in the repo? I looked for a while but couldn't find it.

**Comment by MackerelHunter** [comment]
Nevermind, the module feature is a pretty big advantage over taco. I realized i can update modules in the client. The feature works just like i had envisioned. Very nice!

**Comment by dlamkins** [comment]
That's great to hear!  Glad you found the module in the repo.  Sorry for not specifying.  🙂 

Since things look they're all good now, I'll go ahead and close.  Thanks for reaching out with feedback!

**Comment by Acelya-9028** [comment]
> Version 0.1.9 is now live in the repo if you'd like to give it a shot @angstschweiss 👍

Hi have you a link for the Event Table module sources please? Because I can't find it.

Ok, edit: Found in manifest.json file at https://github.com/Tharylia/Blish-HUD-Event-Table/tree/master/Estreya.BlishHUD.EventTable
