### ISSUE TITLE
Event Table Module Empty

### ISSUE THREAD

**Issue by Werewing** [blish-hud/Blish-HUD#584]
The Event Table stopped stocking/drawing events to the table and now only shows a small white vertical line when enabled.

Worked for about 20 minutes before this error started. Restarting and reinstalling then restarting did not fix the issue.

**Comment by dlamkins** [comment]
This is something likely better asked in the Event Table module's repo: https://github.com/Tharylia/Blish-HUD-Module-Releases/issues

But I'll directly @Tharylia here so that they might be able to assist here.

**Comment by Werewing** [comment]
Sorry, I couldn't find the Event Table's Repo with google, and I couldn't spot the link to it on the Module's Page in Blish Module Hub.

I reposted this there, just in case.

**Comment by dlamkins** [comment]
No worries.  All good.  Most of our troubleshooting happens in Discord anyways, so I apologize that we don't have a clear spot for that stuff here on GitHub.  🙂  When Tharylia is awake, I'm sure they'll take a look.  👍

**Comment by Tharylia** [comment]
I have asked some questions on that in the event table repo.
I think you can close this as it's a duplicate now.
