### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by greaka** [blish-hud/Blish-HUD#6]
### Checklist:
 - [x] Add localization support for API endpoints
 - [x] Add localization for the main UI
 - [ ] Add unified localization format for modules to be translated

### Description

Blish HUD should, where possible, display text in the language of the user. The goal is to have the same language support coverage that the GW2 API has (currently has language support for: English, Spanish, German, French, Korean, and Chinese).

At this point in time, translations for local application strings will likely utilize a free translation tool in lieu of community provided translations.

Language support may be limited in some areas due to missing character sets. A possible/temporary solution to this would be to utilize another font that does contain the necessary characters (at the expense of the font not matching the in-game font). Depending on what character sets are used, it's possible that the GW2 font currently utilized by Blish HUD does actually have the necessary characters. This will need further review in any case.

**Comment by dlamkins** [comment]
A quick update, localization support is essentially complete.  We're using Gw2Sharp for our API requests which supports localization and we're now using resource files to provide translations within the UI.  The remaining work is to finish wiring these up to each other and a setting under **Application Settings**.

**Comment by dlamkins** [comment]
The language drop-down has been wired up and modules now also support reading from translated string assemblies.
