### ISSUE TITLE
Mounts module loads, renders, and responds to hotkey, but doesn't summon mount

### ISSUE THREAD

**Issue by jonchardy** [blish-hud/Blish-HUD#610]
I've been trying to use the mounts module for a while and was excited to see the radial release. However, when I try to use it, it never summons mounts. Are there any particular settings I need for it to work?

Gif:
https://gfycat.com/colossaldimwittedgrebe

Logs:
```
Blish HUD v0.11.4+Branch.tags-v0.11.4.Sha.b345ed98d527f130ab6a0f0c62cdecac019db22c
19:15:19.3905 | INFO  | Blish_HUD.Program | Running Build "Branch.tags-v0.11.4.Sha.b345ed98d527f130ab6a0f0c62cdecac019db22c"
19:15:19.3905 | INFO  | Blish_HUD.Program | Launched from "D:\Jon\Documents\Blish.HUD.0.11.2" with args "--startgw2 2".
19:15:20.8545 | INFO  | Blish_HUD.GameIntegration.WinFormsIntegration | Blish HUD starting Guild Wars 2 with args '"-autologin"'
19:15:21.0507 | INFO  | Blish_HUD.Contexts.FestivalContext | Active festival(s): ""
19:15:21.0507 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
19:15:34.4811 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "markers" ("D:\Jon\Documents\Guild Wars 2\addons\blishhud\markers") was registered.
19:15:34.9350 | INFO  | Blish_HUD.Modules.Module | Module "Mounts (Manlaan.Mounts) v1.2.7" finished loading.
19:15:35.0672 | INFO  | Blish_HUD.Gw2WebApiService | Associated API key "Shaznat.4612" with characters: "Michlei Revhardym, Ihlcemi Mesmorum, Shantaz Eluren, Shaz Nat, Shaznat Alpha, Shazior, Sha Znat"
19:15:35.5916 | INFO  | Blish_HUD.Modules.Module | Module "Pathing (bh.community.pathing) v0.17.3" finished loading.
19:15:48.5743 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs tw_ALL_IN_ONE, markers in 1361 ms for map 1210.
```

**Comment by dlamkins** [comment]
I have a feeling you may have linked the wrong GIF, but in any case, could you please confirm what keybindings you set in the module's settings?  A screenshot of the module's page will help us a ton in identifying what's going on there.  👍

**Comment by jonchardy** [comment]
Sorry about that. Updated the gif. Screenshot:
![blishmount](https://user-images.githubusercontent.com/1202288/155245405-3712d1e5-ff90-45b9-8067-de8a01c037b0.PNG)

**Comment by dlamkins** [comment]
@bennieboj Issue for mounts opened on the Blish HUD repo if you could please take a look.  👍

**Comment by bennieboj** [comment]
Thanks for the feedback, we'll get this sorted.
I'll look at this in more detail after work.
In the meantime could you also post your in-game mount settings keybinds? Thanks!

**Comment by jonchardy** [comment]
Also including graphics options in case that could be involved.

![mounts2](https://user-images.githubusercontent.com/1202288/155324341-3a2bf75d-5681-4715-8118-4dcf417a609d.PNG)
![mounts3](https://user-images.githubusercontent.com/1202288/155324345-27201c6b-ac84-411e-81ff-a2804e492135.PNG)

**Comment by bennieboj** [comment]
Hi,
The keybinds in BlishHUD and the game need to be the same.
I updated the documentation (currently on my branch, will be merged into develop later on):
https://github.com/bennieboj/BlishHud-Mounts/tree/feature/feedback-community#settings
Can you try this and try again? Thanks!

**Comment by dlamkins** [comment]
For reference, this is the image with what you need to match:

![image](https://user-images.githubusercontent.com/1950594/155423476-5a45882f-08c9-4a44-aaa6-569c10589377.png)

**Comment by jonchardy** [comment]
Ah ha, that does it. Thanks!
