### ISSUE TITLE
Blish Hud Crashing while trying to insert Arena.net API key

### ISSUE THREAD

**Issue by Aerasyn** [blish-hud/Blish-HUD#618]
Haven't played Guild Wars in a week or two and when I tried to run it with blish like i always do it crashed. Noticed there was a new verison so i got that and its still crashing but only when i try to insert my api key

**Comment by Aerasyn** [comment]
Apparently things arent working right now becuase End of Dragons imminent release. Disregard.

**Comment by dlamkins** [comment]
Hey!  Glad you were able to figure it out.  Just FYI:

Yes, there is a known issue with some modules and the Guild Wars 2 API currently being down in prep for the EoD release.

If you wanted to continue to use Blish HUD in the meantime, please remove any of the following modules from your modules folder until either the API comes back up (in ~48 hours):
- StreamOut
- EventTable

Remove them from this folder: `\Documents\Guild Wars 2\addons\blishhud\modules`

There is a new version of both of these modules which resolves this issue.  Once you've deleted them from your modules folder, you can download the latest version from the repo safely once you launch Blish HUD again.  👍
