### ISSUE TITLE
Crash when adding API key.

### ISSUE THREAD

**Issue by XIIICaesar** [blish-hud/Blish-HUD#623]
I keep getting a crash whenever I attempt to add my API key. I created a new key just for Blish but it crashes without fail. I paste the key in, yellow circle spins on left, then crash. Doesn't load back up again after game restart either. Only way to get Blish to load again is deleting from addons folder then reinstalling Blish but crashes everytime, even after that, when I add API key. Also, I'm using v0.11.7
[blishhud.20220301-224357.log](https://github.com/blish-hud/Blish-HUD/files/8166491/blishhud.20220301-224357.log)

**Comment by dlamkins** [comment]
Hello!  The Guild Wars 2 API is currently down with no ETA (though it is likely to be back up sometime tomorrow).  It was turned off prior to the expansion to avoid spoilers.  Until it returns adding an API key will not work.

You can track the status of the API here and see when it returns: https://status.gw2efficiency.com/
