### ISSUE TITLE
Can you please customize it for the Wegame version?

### ISSUE THREAD

**Issue by scldt** [blish-hud/Blish-HUD#624]
Thank you for making Blish HUD, it is the best plugin I have ever used.
I am a Chinese GW2 player. there are two versions of GW2 in China, the reseller version and the Wegame version. Currently there are more players entering the world of GW2 with the Wegame version. But Blish HUD doesn't support Wegame version completely.
Can you please customize it for the Wegame version?

**Comment by dlamkins** [comment]
I am unfamiliar with the wegame version.  We've already made accommodations in the past for the other Chinese client, so I suspect we can accommodate this version as well.

Could you confirm what differences there are?
- Is there the extra icon in the wegame version as there is in the other Chinese client?
- Is the exe named something different (the other Chinese client is named `KZW.exe`)?
- Are there other differences that you're aware of that affect compatibility?

**Comment by dlamkins** [comment]
@scldt where you able to find any of the above details for us to be able to move forward with providing support?
