### ISSUE TITLE
method summary not shown when creating a module

### ISSUE THREAD

**Issue by Taschenbuch** [blish-hud/Blish-HUD#632]
**Problem:**
there is no method summary shown on mouse over for all methods in an module. e.g. IModule.Initialize should show this:
![grafik](https://user-images.githubusercontent.com/43114787/158069495-57ef452f-1660-4c7f-b437-2738726f31c8.png)

but instead nothing is visible when creating a module
![grafik](https://user-images.githubusercontent.com/43114787/158069508-17ab1d23-c69f-4ca3-b551-f79a72e809dd.png)

**Potential solution:**
I think the reason is, that the xml documentation is missing:
https://stackoverflow.com/a/43305612/4394435

BlishHUD.0.11.6 package in myModuleProject\packages\BlishHUD.0.11.6 has no .xml files.
Other packages like Gw2Sharp have a Gw2Sharp.xml next to the dll in myModuleProject\Gw2Sharp.1.7.0\lib\netstandard2.0

**Comment by dlamkins** [comment]
Should now  be fixed in #707
