### ISSUE TITLE
feature module repo tab: sort modules by alphabet

### ISSUE THREAD

**Issue by Taschenbuch** [blish-hud/Blish-HUD#635]
sort modules by alphabet in the module repo tab (not as an option, as standard).
Has been suggested multiple times already by others

**Comment by dlamkins** [comment]
We're accepting PRs if you end up beating us to the punch.  👍 Otherwise, yes, it's on the roadmap.

**Comment by Taschenbuch** [comment]
maybe i dig deeper into blish core after i finished my module. currently it is a bit too much. I just wanted to add it here, so it is not lost.
