### ISSUE TITLE
MouseEventArgs doesn't tell you the button

### ISSUE THREAD

**Issue by Snaid1** [blish-hud/Blish-HUD#640]
MouseEventArgs passed into a Click Handler does not include what button was clicked. It would be helpful to be able to detect and appropriately handle if the user left, right, or middle clicks. 

a workaround in the mean time is to use the RightMouseButtonPressed event instead.

I do recognize this may have to wait for BlishHUD to officially support mouse events like what people have been saying regarding mapping the mounts module to a mouse button.

**Comment by dlamkins** [comment]
Confirmed in Discord that this was a misunderstanding of the event type (`.Click` is always a leftmousebuttonreleased event).
