### ISSUE TITLE
Right shift not captured by input

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#641]
It's been reported that right-shift is not getting caught by input boxes.

**Comment by dlamkins** [comment]
I am not currently able to replicate this.

**Comment by entrhopi** [comment]
Me neither. Maybe this is because of special keybindings / AHK of this specific user that override the desired behavior in input boxes?
Needs more investigation.

**Comment by dlamkins** [comment]
Closing for now since we haven't since gotten a complaint about this.
