### ISSUE TITLE
Keybinds can trigger while a textbox is focused.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#642]
It has been reported that keybinds (in this case, the mistwar keybind) can be triggered while a textbox is selected.

**Comment by entrhopi** [comment]
If I remember correctly we had a conversation about if active input in a textbox should block anything but `ESC`.
What undesired behavior are we trying to circumvent here?

**Comment by dlamkins** [comment]
In cases where folks have the keybinding set to just a standard key like "F", it means that it's activated every time they press the key.  🤔 

I've got a change in-bound that will likely fix that specific scenario, though.  I think other input should still be sent, but keybinds specifically should not fire if we're in a Blish HUD input box or a in-game input box.
