### ISSUE TITLE
Decouple certain services from the render loop.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#66]
**QuitarHero at 7/19/2019 8:30:59 PM +00:00**
> So when moving around in-game, markers *want* to stay in their assigned spot, but move around a *little bit* when you move.
> Would it be feasible to have the markers stay perfectly still, or is this unavoidable with how markers are implemented in the world?
> https://gfycat.com/astonishingbitterhare

https://gfycat.com/astonishingbitterhare

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/601873644339068948

**Comment by dlamkins** [comment]
Pulled from our discussion on the issue:

**Freesnöw**
> @QuitarHero  What is your current FPS in game?

**QuitarHero**
> i think the top right of the video is accurate but let me confirm
> yeah it is; I'm getting around ~120 - 130 in that specific area

**Freesnöw**
> Okay cool.  That's probably why.  Right now release builds are locked to a max of 60 FPS and the Gw2MumbleService is still tied to the application's render loop.  That means that, despite it being possible for us to get updates 120-130 times per second, we are only catching 60 of them per second.

**Comment by dlamkins** [comment]
Current services that I have in mind for this are `Gw2MumbleService` and `ArcDpsService`.

**Comment by dlamkins** [comment]
The options listed above are no longer my preferred route to tackle this issue and have been tackled in #368 which provides multiple ways of resolving this issue including the option to sync with the game's framerate which uses draw suppression instead of decoupling the services.
