### ISSUE TITLE
Tooltip for labels of string/int/float settings are missing

### ISSUE THREAD

**Issue by Taschenbuch** [blish-hud/Blish-HUD#662]
current behavior:
when you hover the mouse over a settings LABEL, you can see the tooltip for that setting for keybinding setting and bool setting (checkbox). But when you try the same for string, int and float settings, no tooltip will appear.

expected behavior:
the settings tooltip is always visible. even for string, int and float settings,

example:
good: tooltip visible for bool settings when hovering over the label:
![grafik](https://user-images.githubusercontent.com/43114787/161402131-5282936d-34e7-4eda-be49-0dcdda18e590.png)

bad: no tooltip visible for int setting when hovering over the label:
![grafik](https://user-images.githubusercontent.com/43114787/161402157-8d10fb7a-22c9-4655-bb45-ae7b568e8c3c.png)

**Comment by entrhopi** [comment]
I'll have a quick look at this. Thanks for reporting. :)
