### ISSUE TITLE
Close on gw2 exit

### ISSUE THREAD

**Issue by nezzynaz** [blish-hud/Blish-HUD#665]
It would be helpful to have an option that will automatically close Blish with gw2.

**Comment by entrhopi** [comment]
If I'm not mistaken in the past you could replicate this behavior when you disable `show in tray`.

But we can add an option for that. I'll have a look at this.

**Comment by dlamkins** [comment]
Yes, @entrhopi is correct.  We already support this.  You just need to uncheck the option to stay in the tray.

**Comment by entrhopi** [comment]
Maybe we should clarify this behavior in the description/tooltip then?
Do you think this will be sufficient or should we supply an additional `label` below this settings entry?

**Comment by dlamkins** [comment]
I think there would be some value to revising the name of the setting and/or the setting's description to help make that more clear.  👍
