### ISSUE TITLE
Support showing application and module errors in the UI. 

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#68]
**Andy at 5/21/2019 6:37:39 PM +00:00**
> !suggestion just a small thing. Add a function ``GameService.PrintError(string)`` that allows modules to display a red text in the top half of the screen (like the "this skill is not ready" thing) and fades out.

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/580464240473931796

**Comment by dlamkins** [comment]
We have support for this, kind of. Our ScreenNotification control allows for the described experience. There were also other ways discussed to mark warnings. Including showing something in the corner. 

Modules also have an item under module settings that is intended to let you view the module logs. This could be the appropriate way of showing people module output, warnings, and errors.

**Comment by dlamkins** [comment]
I don't think we'll be moving forward with this.

Modules should be handling their issues gracefully.  If not, we have the log files to review afterwards.  As it stands, if a module throws an exception while loading, the module is disabled automatically.  If a module throws an exception during execution, it should catch that error and handle it appropriately.
