### ISSUE TITLE
FPS Issue: In-game Frame Limiter changes behavior

### ISSUE THREAD

**Issue by NekR** [blish-hud/Blish-HUD#689]
Without Blish HUD running I have stable max FPS at 60, as if frame runs at (1000 / 60) ms interval.
When Blish HUD is running, FPS becomes unstable as if it runs at 16ms internal, so I get ~63 fps.

Same thing happens with the game itself if I disable Vertical Sync, but in this case it's enabled.
I have 2 other addons: dx912prx and Gshade.

**Comment by dlamkins** [comment]
Just to make sure we're on the same page, I'll include some example FPS counts of my own for comparison.

This is my system with the following scenario:

## Without Blish HUD Running

**Guild Wars 2 Frame Limiter:** 60
**Guild Wars 2 Vertical Sync:** No

Here I see a fairly consistent 63 FPS.

![image](https://user-images.githubusercontent.com/1950594/167490257-da1f53eb-042b-4835-a4d5-bd568663cc71.png)

---

**Guild Wars 2 Frame Limiter:** 60
**Guild Wars 2 Vertical Sync:** Yes

Here I see a fairly consistent 60 FPS.

![image](https://user-images.githubusercontent.com/1950594/167490324-50a1a13c-dae9-497f-bf52-71977d153e87.png)

---

## With Blish HUD Running

**Guild Wars 2 Frame Limiter:** 60
**Guild Wars 2 Vertical Sync:** No
**Blish HUD Frame Limiter:** Unlimited (vsync chops it down to 60 anyways on this particular monitor I'm using)
**Blish HUD Vertical Sync:** Yes

Here I see a fairly consistent 63 FPS.

![image](https://user-images.githubusercontent.com/1950594/167490836-a9884b00-88a5-43dc-8894-9f41f5ff79ac.png)

---

**Guild Wars 2 Frame Limiter:** 60
**Guild Wars 2 Vertical Sync:** No
**Blish HUD Frame Limiter:** Unlimited (vsync chops it down to 60 anyways on this particular monitor I'm using)
**Blish HUD Vertical Sync:** Yes

Here I see a fairly consistent 60 FPS.

![image](https://user-images.githubusercontent.com/1950594/167490989-66c38f97-bbdd-4ddb-a786-8cc385aff58f.png)

---

So it seems I can replicate the oddity where in-game FPS sits at 63 with vsync disabled, however, I can't replicate FPS hitting 63 while vsync is enabled (with or without Blish HUD running).

Could you please provide some screenshots of your other graphics settings and confirm if I've done anything wrong/different from your setup with the above?

**Comment by dlamkins** [comment]
@NekR I just wanted to check in and see if you saw my previous update with questions.

**Comment by dlamkins** [comment]
Due to inactivity, I'm going to archive this one, but if you are able to provide any information to answer the above, please don't hesitate to comment again and I'll re-open the issue.
