### ISSUE TITLE
Global volume settings

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#69]
**majσR at 1/25/2019 2:01:28 AM +00:00**
> Small feature request: Volume control from within Blish HUD. Windows volume mixer works but it would be much easier in app.

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/538176549241749536

**Comment by dlamkins** [comment]
Sound loading and playing, in general, needs an overhaul. I think we can use the same library Andy did for the musician module as it definitely appeared to be flexible whereas the MonoGame audio support is fairly limited. 

First steps would be wrapping that library with our `ContentService` and 
`ContentsManager` to allow loading audio from the ref.dat or the module ref. 

I think when playing audio, it would be best to provide a "sound channel" for each volume slider available in GW2. For now, the volume of each channel would probably be the same and tied to a single volume slider, but it allows us to be flexible in the future if options for better set the volume to match the game settings become available.

**Comment by dlamkins** [comment]
While this could still be nice to have, the importance is now much more diminished with the merging of #287 now allowing for the master audio level to be managed automatically.

**Comment by dlamkins** [comment]
Closed by #335
