### ISSUE TITLE
esc key close active Blish HUD window, if focused

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#70]
**Husky at 2/7/2019 9:38:58 PM +00:00**
> not sure if it's been mentioned, but can the Esc key drop the overlay if it's the focussed window?

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/543183919416213525

**Comment by dlamkins** [comment]
> **Suggestion:**
> > Have Esc close Blish HUD windows. It must be a toggle in settings.
> > Reason: GW2 has a toggleable option to close windows via Esc, and in the vein of replicating GW2 functionality, Blish HUD should have it too.
> 
> Esc prioritization should always be given to Blish HUD before GW2.

QuitarHero - https://discordapp.com/channels/531175899588984842/534490472224391169/612368661835022336

**Comment by dlamkins** [comment]
Closed in #443!
