### ISSUE TITLE
Allow blish to run as a separate window

### ISSUE THREAD

**Issue by Snogard** [blish-hud/Blish-HUD#728]
As we all know blish does not play well with wine, but i think that we can take advange of blish features in a slightly inconvinient but workable way.

## What do i expect
I wish i could separate the hud, make it's own separate window and place it on my sencond display. Even if the backgound would sill be black it's still usefull to see paths, markers and other widgets like the achievment tracker or the item search.

example:
![screenshot](https://user-images.githubusercontent.com/23384960/182901968-3d4d8fbe-04cf-47c1-b21a-4eaa258f96ab.png)

**Comment by dlamkins** [comment]
You could do this with the --process launch option to attach it to a different application window. That should give you essentially the same result. 👍

https://blishhud.com/docs/user/launch-options#-p---process-gw2-64

It would even follow that window around so you could reposition it.

**Comment by Snogard** [comment]
This solution is a bit clunky but if it works i guess it's ok :).
Anyway the documentation says that i need the window name too, how do i find out the name of the window?
(autohotkey does not work)
i'm trying to overlay blish over notepad++

**Comment by Snogard** [comment]
nevermind i used a virtual machine to get the information, now i only need to automate the process and then i'll post my results here if you don't mind.

**Comment by dlamkins** [comment]
It may be easier to use pid then instead of the process name (the option below that one I linked).  You could have a script that starts notepad++ and then passes the pid immediately to the new Blish HUD instance. 

And certainly. Feel free to post here.

**Comment by Snogard** [comment]
By pid you mean the pid as seen by wine or the real linux one? if it's the pid seen by wine i'll be more difficult to get that but i could try.
Anyway i tried running blish either before and after opening gw2, but sadly as soon as i select a character blish automatically moves to overlay gw2 instead of notepad. i don't know if it's a wine or blish problem.

this is the command i used:
```
/path/to/wine/lutris-GE-Proton7-24-x86_64/bin/wine "/path/to/npp.8.4.4.portable.x64/notepad++.exe" &
/path/to/wine/lutris-GE-Proton7-24-x86_64/bin/wine "/path/to/Blish HUD 0.11.8-NoTlsCheck118.176/Blish HUD.exe" --process notepad++ --window Notepad++
```

**Comment by dlamkins** [comment]
Ahh, yes, then we will have to use the pid (in wine, I suspect).

Blish HUD can see the real games pid in the mumble API so it's trying to auto re-attach. I think we disable this logic if you manually specify a pid.

**Comment by Snogard** [comment]
Using --pid alone does nothing until i open the game and blish moves to overlay the game anyway.  
Using --pid and --window have the same behaviour as using --process.  
I admit that the pid i use may not be the correct one, i obtained is through the wine console (aka cmd equivalent) using the tasklist command.  
After some research wine may be the cuplrit here according to [this](https://stackoverflow.com/questions/13396052/using-c-sharp-system-diagnostics-process-under-wine-on-linux).



### Logs:

#### steps:
- open notepad++
- open wine console and obtain notepad pid
- open blish 
- open gw2 client

I censored out the character name and the path, the rest is untouched. if you need the logs of my other attemps just ask, but they are not much different than this.

```
Blish HUD v0.11.8-NoTlsCheck118.176+Branch.NoTlsCheck118.Sha.ca89be414eb2781e4fe18cde3467136ebff8b7bf
18:56:10.5070 | INFO  | Blish_HUD.Program | Running PreRelease "NoTlsCheck118.176"
18:56:10.5100 | INFO  | Blish_HUD.Program | Running Build "Branch.NoTlsCheck118.Sha.ca89be414eb2781e4fe18cde3467136ebff8b7bf"
18:56:10.5100 | INFO  | Blish_HUD.Program | Launched from "Z:\path\to\Blish HUD 0.11.8-NoTlsCheck118.176" with args "--pid 680".
18:56:13.4349 | WARN  | Blish_HUD.GameIntegration.Gw2InstanceIntegration | A Win32Exception was encountered while trying to retrieve the process command line.
System.ComponentModel.Win32Exception (0x80004005): File not found.

  at Blish_HUD.ProcessUtil.GetCommandLineInternal (System.IntPtr hProcess) [0x00022] in <57a33e626cb647429f022f9ddf5f335d>:0 
  at Blish_HUD.ProcessUtil.GetCommandLine (System.Diagnostics.Process process) [0x0005a] in <57a33e626cb647429f022f9ddf5f335d>:0 
  at Blish_HUD.GameIntegration.Gw2InstanceIntegration.HandleProcessUpdate (System.Diagnostics.Process newProcess) [0x000b2] in <57a33e626cb647429f022f9ddf5f335d>:0 

18:56:14.1319 | INFO  | Blish_HUD.Gw2WebApiService | Could not find registered API key associated with character "******"
18:56:14.1999 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
18:56:14.1999 | INFO  | Blish_HUD.GameIntegration.ClientTypeIntegration | Detected Guild Wars 2 client to be the Standard version.
18:56:14.3779 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
18:56:14.8889 | INFO  | Blish_HUD.Contexts.FestivalContext | Active festival(s): ""
19:03:50.1632 | WARN  | Blish_HUD.GameIntegration.Gw2InstanceIntegration | A Win32Exception was encountered while trying to retrieve the process command line.
System.ComponentModel.Win32Exception (0x80004005): Resource type not found.

  at Blish_HUD.ProcessUtil.GetCommandLineInternal (System.IntPtr hProcess) [0x00022] in <57a33e626cb647429f022f9ddf5f335d>:0 
  at Blish_HUD.ProcessUtil.GetCommandLine (System.Diagnostics.Process process) [0x0005a] in <57a33e626cb647429f022f9ddf5f335d>:0 
  at Blish_HUD.GameIntegration.Gw2InstanceIntegration.HandleProcessUpdate (System.Diagnostics.Process newProcess) [0x000b2] in <57a33e626cb647429f022f9ddf5f335d>:0 

19:03:59.2821 | INFO  | Blish_HUD.OverlayService | Exiting [4000]!
```
