### ISSUE TITLE
Timers module not working, generates notification.

### ISSUE THREAD

**Issue by CedarD** [blish-hud/Blish-HUD#765]
I am running Blish HUD v0.11.7 and recently Blish notified me of the release of version 0.3.18 of the Timers module. I entered into the Module Repo and updated to the newest version. Blish asked for a restart and I did so. The Timers module was disabled, so I enabled it and it generated the message, "New timers available. Go to settings to update!" In the repo menu, the little green light was on stating I am up to date with the plugin, and it listed the version as 0.3.18. I have tried downgrading, reenabling then updating to the new version with restarts of Blish HUD, etc. I've also tried deleting the module and reinstalling it. The timers don't work and it always generates that message.

**Comment by dlamkins** [comment]
@Dev-Zhao FYI

**Comment by Dev-Zhao** [comment]
@CedarD @dlamkins When that yellow message appears it means there is a new timers pack update, not a module update.

Simply download the latest update in the settings.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/16618046/191870759-de946cba-2435-4019-a088-b5bdbc0f2c39.png">

Sorry for the late reply btw, I just received the Github notification.

**Comment by CedarD** [comment]
Ah! That's good to know, thanks! It might be nice to have some sort of indicator that the timers tab has an update, perhaps a little yellow up-arrow over the hourglass to draw our attention there. In any case, thanks again!

**Comment by Dev-Zhao** [comment]
That's a good idea :)
