### ISSUE TITLE
BlishHUD API Key registration invalid

### ISSUE THREAD

**Issue by Mako-Junkie** [blish-hud/Blish-HUD#779]
Issue seems to have resolved itself. 

So can't offer any advice to those who may find themselves in a similar situation other than to wait it out, I guess.

Sorry for this unnecessary post.

**Comment by dlamkins** [comment]
Hey, sorry about that.  The Guild Wars 2 API was down for a number of hours today which prevented tokens from registering as you saw.  Glad you've seen it's now fixed. 👍
