### ISSUE TITLE
Pathing: manually resetting activated markers

### ISSUE THREAD

**Issue by EukerionGW2** [blish-hud/Blish-HUD#789]
Hi all,
First of all I'd like to thank you for that wonderful piece of software, well done developers!

I've been looking for an answer everywhere and couldn't find it, so I'll ask it here: for the "Pathing" module, with the Tekkit marker pack, as you know when pressing "F" (by default) next to some markers, they disappear to help the user remember which markers they've already visited. With TacO, doing this adds the marker to a file called "activationdata.xml", and one can delete the file contents in order for TacO to show these markers again. I'm trying to understand how to do that with Blish but I haven't found the "activationdata.xml" file or any equivalent in the "markers" folder.

Any suggestions on how to manually reset the activated markers with Blish?

Thanks in advance!
Cheers
- Eukerion

**Comment by dlamkins** [comment]
Hello!  Our equivalent to that file can be found here: 
`\Documents\Guild Wars 2\addons\blishhud\markers\data\states\timers.txt`

Deleting this file and relaunching Blish HUD will restore the icons.

**Comment by EukerionGW2** [comment]
> Hello! Our equivalent to that file can be found here: `\Documents\Guild Wars 2\addons\blishhud\markers\data\states\timers.txt`
> 
> Deleting this file and relaunching Blish HUD will restore the icons.

Great thanks that's exactly what I was looking for! Tested and is working now.

Thanks again
Cheers
-Eukerion

**Comment by dlamkins** [comment]
Everything that is toggled off by a behavior is in there.

Achievements themselves are not if marked in the XML with an achievement attribute.  Those are pulled from the API, but the rest that are based on manual triggers and not tied to an achievement will be in this file.
