### ISSUE TITLE
Show Module Disable State at a glance in Manage Modules Tab

### ISSUE THREAD

**Issue by Hotklou2404** [blish-hud/Blish-HUD#827]
Currently you have to click on each module in the Manage Modules tab to determine which of your installed modules are currently enabled and disabled. It would be much more convenient if the module's name were displayed in a different colour depending on whether it is enabled or not (such as it being grayed-out when the module is disabled), or if there were a little icon that you could look at next to its name to see whether it is enabled or disabled.

**Comment by dlamkins** [comment]
How does something like this look?

![image](https://user-images.githubusercontent.com/1950594/211618354-858a4818-803b-48d9-92ae-835069e37437.png)

**Comment by dlamkins** [comment]
You can test this new feature with the copy I've uploaded here, and it will be available in our next prerelease.  👍 
[Blish HUD.1.0.1-PullRequest0831.11.zip](https://github.com/blish-hud/Blish-HUD/files/10385671/Blish.HUD.1.0.1-PullRequest0831.11.zip)

**Comment by dlamkins** [comment]
We'll tone down the icons in a future release.
