### ISSUE TITLE
No obvious way to uninstall Blish

### ISSUE THREAD

**Issue by Siofral** [blish-hud/Blish-HUD#848]
I need a way to completely uninstall Blish. I'm not seeing one and am not finding anything helpful on the web.

**Comment by dlamkins** [comment]
Blish HUD doesn't really install. It stores your modules and settings under a single folder that you can just delete or ignore after you delete the exe you downloaded. This folders path is listed on this page:

https://blishhud.com/docs/user/getting-started#3-launch-blish-hudexe

**Comment by Siofral** [comment]
According to my search in Windows Blish has files scattered over multiple directories. I can hunt them all down and delete them but that's an inefficient and messy way to handle the problem. Again, I reiterate. I would like a comprehensive uninstaller so when I reinstall I know I'm getting a completely clean install. I've got an issue I haven't been able to track down. A clean uninstall is my next step.

**Comment by dlamkins** [comment]
You are welcome to list what directories your search refurned, but there is
no uninstaller as there is no installer.

We also don't believe 'fresh installs' to be an effective method of
troubleshooting and recommed reaching out with your issue in our Discord
channel for direct assistance.  Chances are a copy of your logs and some
assistance from somebody in the channel will result in a much faster fix. 👍

**Comment by Siofral** [comment]
Thanks. I'm trying to isolate a problem. Removing Blish is one of the steps to a wider scope of troubleshooting.
