### ISSUE TITLE
ArcDPS Addon (Scrolling Combat Text) showing skill names as "Unknown" and stops working after a while.

### ISSUE THREAD

**Issue by jblanco2623** [blish-hud/Blish-HUD#852]
Appart from not appearing the skill names (The "skill.Name" appears as "Unknown" when displaying it) it works fine, but after a while of playing the addon stops working, but i can still open the addon ArcDPS without any problem.<br>
I tried to deactivate and activate the module again but doesn't seem to work, once it goes down it doesn't come back until i restart the whole game and BlishHUD.

Edit: Small update, it seem it happens when i enter the Shroud with the necromancer. I tested it and played for an hour without using it and it worked fine, just the "Unknown" at the skill names.

**Comment by jblanco2623** [comment]
Found the Issue and the solution:
- Issue:

**Comment by jblanco2623** [comment]
Found the Issue and the solution:
- Issue: Due to the Computer System being in a different language than the game it generates a file with the skills in the computer system language, but the game tries to obtain said names in the game language, an example is:
         -  Computer System Language: Spanish
         -  Game Language: English
         -  File with the skills generated in Spanish
- Solution: Uninstall the addon "Scrolling Text" from BlishHUB, change the language of your computer system to the language you are using in game, re-install the addon and it should work now.

**Comment by dlamkins** [comment]
@Tharylia worth taking a look when you have a moment.

**Comment by Tharylia** [comment]
You don't actually need to change your OS language. It's sufficient to match gw2 and blish language. Maybe delete the skills.json and last_updated file to force a reload
