### ISSUE TITLE
Modules listing buggy

### ISSUE THREAD

**Issue by golddragon007** [blish-hud/Blish-HUD#859]
Certain modules do not show up in the modules repository.
Like:
- Universal search
- Trading post watcher

Also selecting the different checkboxes to filter the modules makes the list constantly empty after a while or some combination.
Also shows sometimes updates when there's no any or there's 1 update but shows 3.

Blishud version: 1.0.0

**Comment by dlamkins** [comment]
1. The missing modules are either removed from the repo (the universal search module) or are prerelease only (you can enable in your overlay settings).

2. The toggles have already been fixed for the next release.

3. The notifications are about prereleases that you don't have visible.
