### ISSUE TITLE
UI becomes unresponsive

### ISSUE THREAD

**Issue by shrugal** [blish-hud/Blish-HUD#893]
I had this issue for over a year now: Blish HUD becomes unresponsive to mouse/keyboard interactions seemingly at random. Things like markers still update properly, it just doesn't react to mouse hover or clicks. The mount module still kinda works. I can mount and unmount the default mount, but the wheel doesn't show up anymore when holding the hotkey down.

Some days it's fine for hours, but others (like right now) it happens every 5 minutes. I have tried disabling different modules, but nothing changed. The task bar menu still works though, so I can always shut it down and restart it again.

Here is the log from the last time it happened, around 16:17: https://gist.github.com/shrugal/51818ec3db73882807c7ca493ca4eda1

**Comment by dlamkins** [comment]
This issue repository is for tracking known technical issues and not for user troubleshooting. If you are looking for assistance with Blish HUD, please reach out in our Discord channel: https://link.blishhud.com/discordhelp

**Comment by shrugal** [comment]
Sorry if I misunderstood this, but I'm pretty sure this is a technical issue and not something on my part. I didn't do anything special afaik.

**Comment by dlamkins** [comment]
All user troubleshooting is done in the discord. If we discover a
reproducible cause then we would track it here, but we no longer offer
troubleshooting through these issues. It's slow, mixes with more trackable
issues, etc.

In this case, I suspect we'd be looking for an external cause seeing as we
don't have other users reporting this issue and you seem to be experiencing
it even with no modules enabled.
