### ISSUE TITLE
API Key Unknown

### ISSUE THREAD

**Issue by TaveDerren** [blish-hud/Blish-HUD#908]
Hi,
I've been using blishhud for a couple of weeks and a few days ago any addon related to api keys stopped working. I then checked the settings and it stated that it couldn't load the key anymore, I then deleted it and tried adding it again, but it now only shows unknown and I can't register it or any other api key even new ones.

**Comment by MelBLT** [comment]
Having the same issue.

**Comment by dlamkins** [comment]
@MelBLT The Guild Wars 2 web API is currently down. We have this posted on our website and they've announced it in the official forums. 

It will be back up sometime on the 23rd. Until then, this is expected behavior. I apologize for the trouble. 👍
