### ISSUE TITLE
Feature request: sort modules with updates first

### ISSUE THREAD

**Issue by nightzirch** [blish-hud/Blish-HUD#909]
In the name of user experience, I would suggest sorting installed modules with available updates at the top of the module list. In addition I would suggest sorting the modules under "Manage Modules" alphabetically as you do in the Module Repo list.

**Comment by dlamkins** [comment]
We provide the option to show modules with pending updates already via the filter in the cog.  The next option we intend to provide is an update all button.

For the latter, we are already tracking that here: https://github.com/blish-hud/Blish-HUD/issues/826
