### ISSUE TITLE
Trail width does not match TacO's trail width.

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#92]
**QuitarHero at 7/17/2019 10:32:37 PM +00:00**
> I would like to suggest an attribute that allows for Trail Size modification, or at the very least change the default size of trails to be what Tac0's default is.

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/601179481524273197

**Comment by dlamkins** [comment]
>Oh, and also I found out why the Blish HUD trails were the wrong size compared to the TacO ones.  TacO has the trails set to be 40 wide: 20 on each side.  I was accidentally setting it to be 40 on each side, so I was just off by a factor of 2.  Easy fix. 🙂 

https://discordapp.com/channels/531175899588984842/534490472224391169/604185389682393098
