### ISSUE TITLE
Forcing user to watch Youtube video.

### ISSUE THREAD

**Issue by Tcip** [blish-hud/Blish-HUD#931]
I'm not having an issue but annoyance.

Why are you forcing the user to watch a Youtube video for 'Getting Started'. No readme file in the .zip file or any info on the video. Just forcing user to whatch the video..

**Comment by dlamkins** [comment]
Our website also has a getting started guide which covers most of the same points. 

https://blishhud.com/docs/user/getting-started

Further, our GitHub issues are only for technical items, so I will be closing this issue.
