### ISSUE TITLE
The pathing module break if Blish is blocked by firewall.

### ISSUE THREAD

**Issue by TikoTako** [blish-hud/Blish-HUD#942]
It show the path in the game window as usual but not in the minimap or the map 🤨

**Comment by dlamkins** [comment]
The pathing module has to pull data from the API in order to determine the ratios needed to render on the minimap, so this expected. I'd recommend not blocking the pathing module for the best experience. 

This repo also isn't for user troubleshooting. Please use discussions or join our Discord.
