### ISSUE TITLE
Suggestion Manage Modules tab: show different hint/button when no modules are installed

### ISSUE THREAD

**Issue by Taschenbuch** [blish-hud/Blish-HUD#948]
current behavior:
- see screenshot below
- suggest manually installing modules
- button opens modules in windows explorer

suggested behavior:
- Show a different hint like "You dont currently have any modules. Install some modules via "Module Repo" Tab"
- remove button OR let it open the "Module Repo" tab instead

![image](https://github.com/blish-hud/Blish-HUD/assets/43114787/9fdc3dd0-1a87-4098-9ed8-305f4c3373eb)

**Comment by dlamkins** [comment]
Good ideas.  Duplicate of #519.  🙂
