### ISSUE TITLE
Blish and Nexus icons are in the same place on the screen

### ISSUE THREAD

**Issue by kazerniel** [blish-hud/Blish-HUD#972]
Not sure which repository this is more relevant to, but as I can't seem to open tickets in https://github.com/RaidcoreGG/Nexus I'm putting it here (and tagging @DeltaGW2 @RaidcoreGG) ⤵

The two apps have their icon in the same location; could one of the apps be capable of sensing the other's presence and shift its icon to the right? Or what [TacO](https://github.com/BoyC/GW2TacO/) did, and put its icon on the row below.

(I'm using 1920x1080 resolution under Win 10.)

**Comment by dlamkins** [comment]
There is a module called "Nexus Shim". Add it and enable it in Blish HUD. This module makes Blish HUD aware of Nexus' icons.

**Comment by kazerniel** [comment]
Thanks!
